spring:
  application:
    name: spring-observability-demo
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v4
    vectorstore:
      redis:
        initialize-schema: true # 是否⾃动创建索引结构
        index-name: spring-ai-observability # 向量索引名称
        prefix: "observability:" # Redis Key 前缀
management:
  tracing:
    sampling:
      # trace 采样信息, 记录每个请求
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  data:
    redis:
      url: redis://127.0.0.1:6379