server:
  port: 8081
spring:
  application:
    name: chat-bot-service
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/sql/schema-mysql.sql
    mcp:
      client:
        request-timeout: 60000
        stdio:
          servers-configuration: classpath:/mcp/mcp-servers-config.json
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      redis:
        initialize-schema: true # 是否⾃动创建索引结构
        index-name: seven-chat-bot # 向量索引名称
        prefix: "rag:" # Redis Key 前缀
  data:
    redis:
      url: redis://127.0.0.1:6379
  datasource:
    username: root
    password: 568313
    url: jdbc:mysql://localhost:3306/seven_chat_bot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n%wEx"
data:
  is-load: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true #配置驼峰⾃动转换